lab2/front/MVCClient/Models/IndexVM.cs
namespace MVCClient.Models;

public class IndexVM
{
    public IEnumerable<User> Users { get; set; }
    public IEnumerable<Product> Products { get; set; }
}

lab2/front/MVCClient/Models/Product.cs
namespace MVCClient.Models;

public class Product
{
    public int Id { get; set; }
    public string Name { get; set; }
    public decimal Price { get; set; }
}

lab2/front/MVCClient/Models/User.cs
namespace MVCClient.Models;

public class User
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Surname { get; set; }
    public string Address { get; set; }
}

lab2/front/MVCClient/Controllers/HomeController.cs
using System.Collections;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MVCClient.Models;
using Newtonsoft.Json;

namespace MVCClient.Controllers;

public class HomeController : Controller
{
    

    public IActionResult Index()
    {
        IndexVM indexVm = new IndexVM();
        
        IEnumerable<User> users = null;

        using (var client = new HttpClient())
        {
            client.BaseAddress = new Uri("http://192.168.49.2:80/api/");
            //HTTP GET
            var responseTask = client.GetAsync("user");
            responseTask.Wait();

            var result = responseTask.Result;
            
            var readTask = result.Content.ReadAsStringAsync();
            readTask.Wait();

            string res = readTask.Result;

            users = JsonConvert.DeserializeObject<IEnumerable<User>>(res);
            
            
        }
        
        IEnumerable<Product> products = null;

        using (var client = new HttpClient())
        {
            client.BaseAddress = new Uri("http://192.168.49.2:80/api/");
            //HTTP GET
            var responseTask = client.GetAsync("product");
            responseTask.Wait();

            var result = responseTask.Result;
            
            var readTask = result.Content.ReadAsStringAsync();
            readTask.Wait();

            string res = readTask.Result;

            products = JsonConvert.DeserializeObject<IEnumerable<Product>>(res);
            
            
        }

        indexVm.Users = users;
        indexVm.Products = products;
        
        return View(indexVm);
    }

    
    

    
}

lab2/front/MVCClient/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using MVCClient.Models;

namespace MVCClient.Controllers;

public class ProductController : Controller
{
    
    
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Create(Product product)
    {
        using (var client = new HttpClient())
        {
            client.BaseAddress = new Uri("http://192.168.49.2:80/api/");
            var postTask = client.PostAsJsonAsync<Product>("product", product);
            postTask.Wait();
            return RedirectToAction("Index", "Home");
        }
    }
}

lab2/front/MVCClient/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using MVCClient.Models;

namespace MVCClient.Controllers;

public class UserController : Controller
{
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Create(User user)
    {
        using (var client = new HttpClient())
        {
            client.BaseAddress = new Uri("http://192.168.49.2:80/api/");
            var postTask = client.PostAsJsonAsync<User>("user", user);
            postTask.Wait();
            return RedirectToAction("Index", "Home");
        }
    }
}

lab2/front/MVCClient/Views/Home/Index.cshtml
@model IndexVM;
@{
    
    
}

<div class="text-center">
    <h1 class="display-4">Users</h1>
    @foreach (User u in Model.Users)
    {
        {
            <p>ID: @u.Id</p>
            <p>Name: @u.Name</p>
            <p>Surname: @u.Surname</p>
            <p>Address: @u.Address</p>
        }
    }
    <a asp-controller="User" asp-action="Create" class="btn btn-primary">Create new user</a>
    <hr/>
    <h1 class="display-4">Products</h1>
    @foreach (Product p in Model.Products)
                {
                    <p>ID: @p.Id</p>
                    <p>Name: @p.Name</p>
                    <p>Price: @p.Price</p>
                }
    <a asp-controller="Product" asp-action="Create" class="btn btn-primary">Create new product</a>
</div>

lab2/front/MVCClient/Views/Product/Create.cshtml
@model Product
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Product Creation</h2>
            <hr/>
        </div>
        <div class="mb-3">
            <label asp-for="Id"></label>
            <input asp-for="Id" class="form-control"/>
            <span asp-validation-for="Id" class="text-danger"></span>
        </div>
        
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control"/>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
                    <label asp-for="Price"></label>
                    <input asp-for="Price" class="form-control"/>
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
        <button type="submit" class="btn btn-primary" style="width: 150px"><i class="bi bi-check-circle"></i> Create</button>
        <a asp-controller="Home" asp-action="Index" class="btn btn-secondary"><i class="bi bi-box-arrow-left"></i> Back</a>
    </div>
</form>
@section Scripts
{

@{
    <partial name="_ValidationScriptsPartial"/>
}
}

lab2/front/MVCClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - MVCClient</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/MVCClient.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCClient</a>
            
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - MVCClient 
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

lab2/front/MVCClient/Views/User/Create.cshtml
@model User
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">User Creation</h2>
            <hr/>
        </div>
        <div class="mb-3">
            <label asp-for="Id"></label>
            <input asp-for="Id" class="form-control"/>
            <span asp-validation-for="Id" class="text-danger"></span>
        </div>
        
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control"/>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Surname"></label>
            <input asp-for="Surname" class="form-control"/>
            <span asp-validation-for="Surname" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Address"></label>
            <input asp-for="Address" class="form-control"/>
            <span asp-validation-for="Address" class="text-danger"></span>
        </div>
        
        <button type="submit" class="btn btn-primary" style="width: 150px"><i class="bi bi-check-circle"></i> Create</button>
        <a asp-controller="Home" asp-action="Index" class="btn btn-secondary"><i class="bi bi-box-arrow-left"></i> Back</a>
    </div>
</form>
@section Scripts
{

@{
    <partial name="_ValidationScriptsPartial"/>
}
}